Routing and clock
Sinonaz/learn.javascript.react pull request #7
Opened 2024-10-13 15:25 UTC by Sinonaz

2024-10-16 16:13 UTC, zubkov7 commented on src/components/App/App.jsx
> +						</Layout>
уже не нужно

2024-10-16 16:15 UTC, zubkov7 commented on src/components/Menu/Menu.jsx
> +		</div>
какая тут задумка была? на pathname плохая практика завязываться, проблему можно решить правильном композицией компонентов

2024-10-16 16:15 UTC, zubkov7 commented on src/components/Restaurant/Restaurant.jsx
> +			{user.isAuth && pathname.endsWith("/reviews") && <ReviewForm />}
тут тоже

2024-10-16 16:16 UTC, zubkov7 commented on src/components/RestaurantTab/RestaurantTab.jsx
> +				isActive
можно classNames(styles.restaurantTab, isActive && styles.active)

2024-10-16 16:17 UTC, zubkov7 requested changes
нужно решить проблему завязки компонентом правильной композицией и необходимые куски вынести на компоненты страниц, а не скрывать внутри. В дальнейшем эта логика может легко забыться и возникнет баг при переиспользовании компонента

2024-10-19 11:12 UTC, Sinonaz commented on src/components/Menu/Menu.jsx
> +		</div>
Поначалу не до конца разобрался в функционале роутинга. Исправил

2024-10-20 12:07 UTC, zubkov7 approved these changes

2024-10-20 19:18 UTC, merged